# -*- coding: utf-8 -*-

import scrapy

#######################################################################################
#
#  Page Data
#######################################################################################


class SeoSpiderItem(scrapy.Item):
    Url=scrapy.Field()
    Referrer=scrapy.Field()
    ResponseTime=scrapy.Field()
    Title = scrapy.Field()
    TitleLen=scrapy.Field()
    MetaDesc=scrapy.Field()
    MetaDescLen=scrapy.Field()
    MetaKwds=scrapy.Field()
    MetaCharset=scrapy.Field()
    Canonical=scrapy.Field()
    Lang=scrapy.Field()
    Doctype=scrapy.Field()
    PageSize=scrapy.Field()
    PageTextToHtmlRatio=scrapy.Field()
    PageTextPercentage=scrapy.Field()
    ExcessSpacesLen=scrapy.Field()
    HtmlCommentsLen=scrapy.Field()
    HtmlComments=scrapy.Field()
    # global
    MetaRobots=scrapy.Field()
    Favicon=scrapy.Field()
    GPublisher=scrapy.Field()
    GAuthor=scrapy.Field()
    Tables=scrapy.Field()
    TablesNum=scrapy.Field()
    TablesNestingLevel=scrapy.Field()
    H1=scrapy.Field()
    H2=scrapy.Field()
    H3=scrapy.Field()
    H4=scrapy.Field()
    H5=scrapy.Field()
    H6=scrapy.Field()
    H1Num=scrapy.Field()
    H2Num=scrapy.Field()
    H3Num=scrapy.Field()
    H4Num=scrapy.Field()
    H5Num=scrapy.Field()
    H6Num=scrapy.Field()
    CSSFilesNum=scrapy.Field()
    JsFilesNum=scrapy.Field()
    InlineStylesNum=scrapy.Field()
    Pdfs=scrapy.Field()
    # article content only 
    WordCount=scrapy.Field() 
    LinksExternal=scrapy.Field()
    LinksInternal=scrapy.Field()
    LinksInComments=scrapy.Field()
    LinksExternalNum=scrapy.Field()
    LinksInternalNum=scrapy.Field()
    LinksAndTitleAttr=scrapy.Field()
    LinksWithTitleNum=scrapy.Field()
    LinksWithoutTitleNum=scrapy.Field()
    LinksNoFollowNotInComm=scrapy.Field()
    LinksNoFollowNum=scrapy.Field()
    Imgs=scrapy.Field()
    ImgsNum=scrapy.Field()
    ImgsWithAltOrTitle=scrapy.Field()
    ImgsWithAltOrTitleNum=scrapy.Field()
    ImgsWithoutAltOrTitle=scrapy.Field()
    ImgsWithoutAltOrTitleNum=scrapy.Field()
    PNum=scrapy.Field() 
    PLenMax=scrapy.Field() 
    BadAnchors=scrapy.Field()
    LinksToFiles=scrapy.Field()
    FacebookStats=scrapy.Field()
    FacebookTotalCount=scrapy.Field()
    PostCommentsNum=scrapy.Field()

